# -*- coding: utf-8 -*-
"""
Created on Sun Oct 27 13:14:45 2019

@author: kubac
"""
"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the
user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed
correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many
“cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track
of the number of guesses the user makes throughout teh game and tell the user at the end.


Say the number generated by the computer is 1038. An example interaction could look like this:
  
Welcome to the Cows and Bulls Game!
 
 Enter a number:
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
"""

import random

def generator():
    return '4271'#str(random.randint(1000,9999))

def zapytanie():
    return input("podaj liczbe:")

def bulls(strzal,liczba):
    bulls=0
    for item in range(0,len(liczba)):
        if strzal[item] == liczba[item]:
            bulls = bulls + 1
    return bulls
            
def cows(strzal,liczba):
    cows=0
    for item in range(0,len(liczba)):
        for item2 in range(0,len(liczba)):
            if item2 != item:
                if strzal[item] == liczba[item2]:
                     cows = cows + 1
    return cows
  
if __name__=="__main__":          
    liczba=generator()
    gra = True
    proby = 0
    while(gra):
        strzal=zapytanie()
        proby = proby + 1
        krowy=cows(strzal,liczba)
        byki=bulls(strzal,liczba)
        
        if byki == 4:
            print('brawo, odgadles liczbe %s'%liczba + ' za' +' %d'%proby + ' razem.')
            break
        else:
            print('krowy: %d' %krowy)
            print('byki: %d' %byki)









